CREATE TABLE IF NOT EXISTS events
(
    id        BIGINT    NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bot_id    BIGINT    NOT NULL,
    user_id   BIGINT    NOT NULL,
    type      INT       NOT NULL, -- 1 - нажатие, 2 - метка
    create_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS clicker_info
(
    id        BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bot_id    BIGINT       NOT NULL,
    name      VARCHAR(100) NOT NULL,
    slug      VARCHAR(100) NOT NULL,
    create_at TIMESTAMP    NOT NULL,
    update_at TIMESTAMP    NOT NULL,
    CONSTRAINT slug_unique UNIQUE (bot_id, slug)
);

CREATE TABLE IF NOT EXISTS click_events
(
    event_id        BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    clicker_info_id BIGINT NOT NULL REFERENCES clicker_info (id)
);

CREATE TABLE IF NOT EXISTS utm_sources
(
    id        BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100) NOT NULL,
    create_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_mediums
(
    id        BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100) NOT NULL,
    create_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_campaigns
(
    id        BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100) NOT NULL,
    create_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_contents
(
    id        BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100) NOT NULL,
    create_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_terms
(
    id        BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100) NOT NULL,
    create_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS utm_events
(
    event_id    BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    source_id   BIGINT NOT NULL REFERENCES utm_sources (id),
    medium_id   BIGINT NOT NULL REFERENCES utm_mediums (id),
    campaign_id BIGINT NOT NULL REFERENCES utm_campaigns (id),
    content_id  BIGINT REFERENCES utm_contents (id),
    term_id     BIGINT REFERENCES utm_terms (id),
    is_new_user BOOLEAN
);

CREATE TABLE IF NOT EXISTS utm_links
(
    id          VARCHAR(36) NOT NULL PRIMARY KEY,
    bot_id    BIGINT       NOT NULL,
    source_id   BIGINT      NOT NULL REFERENCES utm_sources (id),
    medium_id   BIGINT      NOT NULL REFERENCES utm_mediums (id),
    campaign_id BIGINT      NOT NULL REFERENCES utm_campaigns (id),
    content_id  BIGINT REFERENCES utm_contents (id),
    term_id     BIGINT REFERENCES utm_terms (id),
    create_at   TIMESTAMP   NOT NULL
);
