CREATE TABLE IF NOT EXISTS newsletter
(
    id         VARCHAR(36) NOT NULL PRIMARY KEY,
    bot_id     BIGINT      NOT NULL,
    messenger  INT         NOT NULL,
    send_at    TIMESTAMP   NOT NULL,
    is_deleted BOOLEAN     NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS message
(
    id            BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform_id       VARCHAR(20) NOT NULL,
    newsletter_id VARCHAR(36) NOT NULL REFERENCES newsletter (id) ON DELETE CASCADE,
    chat_id       VARCHAR(20) NOT NULL
);