CREATE TABLE IF NOT EXISTS users
(
    id             BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    surname        VARCHAR(50)  NOT NULL,
    name           VARCHAR(50)  NOT NULL,
    username       VARCHAR(50)  NOT NULL,
    email          VARCHAR(80)  NOT NULL,
    password       VARCHAR(250) NOT NULL,
    salt           VARCHAR(100) NOT NULL,
    registered_at  TIMESTAMP    NOT NULL,
    enabled        BOOLEAN      NOT NULL,
    email_verified BOOLEAN      NOT NULL,
    CONSTRAINT username_unique UNIQUE (username),
    CONSTRAINT email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS companies
(
    id         BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255) NOT NULL,
    owner_id   BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    slug       VARCHAR(255) NOT NULL,
    logo_url   VARCHAR(255),
    bg_color   VARCHAR(8)   NOT NULL,
    text_color VARCHAR(8)   NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT company_unique UNIQUE (id, slug)
);

CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT role_unique UNIQUE (id, name)
);

CREATE TABLE IF NOT EXISTS projects
(
    id           BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id   BIGINT       NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    bot_id       BIGINT,
    name         VARCHAR(60)  NOT NULL,
    description  TEXT,
    slug         VARCHAR(80)  NOT NULL,
    logo_url     VARCHAR(255),
    bg_color     VARCHAR(8)   NOT NULL,
    text_color   VARCHAR(8)   NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    api_key      VARCHAR(40),
    webhook_path VARCHAR(255),
    active       BOOLEAN      NOT NULL,
    CONSTRAINT projects_unique UNIQUE (api_key)
);

CREATE TABLE IF NOT EXISTS users_roles
(
    id      BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT users_roles_unique UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS companies_users
(
    id         BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT companies_users_unique UNIQUE (user_id, company_id)
);

CREATE TABLE IF NOT EXISTS projects_users
(
    id         BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT projects_users_unique UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS company_invitations
(
    id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT      NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    email      VARCHAR(80) NOT NULL,
    code       VARCHAR(7)  NOT NULL,
    confirm    BOOLEAN     NOT NULL,
    send_at    TIMESTAMP,
    confirm_at TIMESTAMP
);
