version: '3'

services:

  eureka-server:
    image: ghcr.io/mark1708/bf-eureka-server:v1.0.0
    environment:
      - PROFILES=prod
    networks:
      - npm-public
      - backend
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1

  config-server:
    image: ghcr.io/mark1708/bf-config-server:v1.0.0
    environment:
      - PROFILES=prod
      - GIT_USERNAME=Mark1708
      - GIT_PASS=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
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1

networks:
  backend:
    external: true
  npm-public:
    external: true
