version: '3'

services:
  agent:
    image: portainer/agent:2.16.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - npm-public
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.16.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /mnt/portainer:/data
    networks:
      - npm-public
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.labels.keycloak == true

networks:
  npm-public:
    external: true
