CREATE TABLE IF NOT EXISTS files
(
    id          BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_id  BIGINT       NOT NULL,
    bot_id      BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    path        VARCHAR(500) NOT NULL,
    description VARCHAR(500) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    public_link BOOLEAN      NOT NULL,
    CHECK ( length(name) >= 1 ),
    CHECK ( length(path) >= 1 ),
    CHECK ( length(description) >= 1 ),
    CONSTRAINT file_unique UNIQUE (bot_id, slug)
);

CREATE TABLE IF NOT EXISTS public_links
(
    id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_id    BIGINT      NOT NULL REFERENCES files (id) ON DELETE CASCADE,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    token      VARCHAR(32) NOT NULL
);